<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\GestionArchivosEscaneados.Application\GestionArchivosEscaneados.Application.csproj" />
    <ProjectReference Include="..\GestionArchivosEscaneados.Constants\GestionArchivosEscaneados.Constants.csproj" />
    <ProjectReference Include="..\GestionArchivosEscaneados.Models\GestionArchivosEscaneados.Models.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-MasivosWorker-30159da6-1dab-4d20-8789-e80cc6e3408f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Update="web.config">
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Update="wwwroot\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Update="Prompts\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
