<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GestionArchivosEscaneados.Models\GestionArchivosEscaneados.Models.csproj" />
    <ProjectReference Include="..\GestionArchivosEscaneados.Constants\GestionArchivosEscaneados.Constants.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BarCode" Version="2026.4.2" />
    <PackageReference Include="IronPdf" Version="2026.3.1" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.3" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.8" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
