namespace GestionArchivosEscaneados.Constants;

public static class EtiquetasUi
{
    public const string TituloApp = "Gestión archivos escaneados";
    public const string Login = "Iniciar sesión";
    public const string Usuario = "Usuario";
    public const string Calendario = "Seleccione una fecha";
    public const string Dashboard = "Resumen del día";
    public const string NoProcesados = "Documentos no procesados";
    public const string Procesados = "Procesados";
    public const string Pendientes = "No procesados";
    public const string CodigoBarras = "Código de barras";
    public const string Procesar = "Procesar";
    public const string ProcesarLote = "Procesar documentos";
    public const string Ver = "Ver";
    public const string CerrarSesion = "Cerrar sesión";
    public const string ListosParaProcesar = "listos para procesar";
    public const string SinDocumentosPendientes = "No hay documentos pendientes.";
    public const string SeleccionarDocumento = "Seleccione un documento para previsualizarlo.";
    public const string VistaPrevia = "Vista previa";
    public const string VolverResumen = "Volver al resumen";
    public const string Archivo = "Archivo";
    public const string Fecha = "Fecha";
    public const string FechaFactura = "Fecha factura";
    public const string Eliminar = "Eliminar";
    public const string ConfirmarEliminacion = "Confirmar eliminación";
    public const string Cancelar = "Cancelar";
    public const string Transacciones = "Transacciones";
    public const string UsuariosEscaneo = "Usuarios con escaneos";
    public const string FechasEscaneo = "Fechas de escaneo";
    public const string DocumentosProcesados = "Documentos procesados";
    public const string IdRegistro = "Id";
    public const string Soporte = "Soporte";
    public const string IdPaciente = "Id paciente";
    public const string IdBodega = "Id bodega";
    public const string IdCartera = "Id cartera";
    public const string Procesado = "Procesado";
    public const string FechaCreacion = "Fecha registro";
    public const string FiltrarColumna = "Filtrar…";
    public const string SinUsuarios = "No hay usuarios con escaneos registrados.";
    public const string SinFechas = "No hay fechas registradas para este usuario.";
    public const string SinDocumentos = "No hay documentos para esta fecha.";
    public const string VolverUsuarios = "Volver a usuarios";
    public const string VolverFechas = "Volver a fechas";
    public const string TotalArchivos = "Total archivos";
    public const string TotalEscaneo = "Total escaneo";
    public const string FilasPorPagina = "Filas por página";
    public const string Pagina = "Página";
    public const string De = "de";
    public const string Anterior = "Anterior";
    public const string Siguiente = "Siguiente";
    public const string Mostrando = "Mostrando";
    public const string ArchivosFiltrados = "Archivos filtrados";
}
